GET localhost:8080/flower
accept: application/json

###
GET localhost:8080/flower/dsl
accept: application/json

###
GET localhost:8080/flower/jdsl
accept: application/json

###
GET localhost:8080/flower/jdsl?ids=1,3
accept: application/json

###
PUT localhost:8080/flower/jdsl
content-type: application/json

{
  "id": 1,
  "name": "changed flower2",
  "price": 999999,
  "message" : "changed message"
}

###
DELETE localhost:8080/flower/jdsl?id=1